version: '3.7'

services:
  jaeger:
    image: jaegertracing/all-in-one
    hostname: jaeger
    restart: always
    ports:
      - '16686:16686'
      - '13133:13133'
      - '4317:4317'
  prometheus:
    image: prom/prometheus:v2.42.0
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"